### PR TITLE
Ignore IDE and OS specific files

### PR DESCRIPTION
**Pull request by Jodge**

### CODE REVIEW

**Comment by Jodge** [comment]
Hmm we are making assumptions that the user would have already configured their global gitignore at the time of cloning the repo? What is the probability of that?

**Comment by SCdF** [comment]
> Hmm we are making assumptions that the user would have already configured their global gitignore at the time of cloning the repo? What is the probability of that?

The flow here would be that the user would see these files when they tried to commit something and learn how to globally ignore them.

The alternative is that we put in the dozens of common patterns for various text editors, ides and file metadatas against every base gitignore, which doesn't seem sustainable.

**Comment by SCdF** [comment]
Remember you don't have to have *already* done it. If people accidentally commited these files we would reject the PRs and tell them about this git feature.

**Comment by Jodge** [comment]
Ok that's fine

**Pull request closed without merging**
